---
title: "CodeBook"
author: "Angel Medina"
date: "Friday, February 20, 2015"
output: html_document
---
This CodeBook explain the meaning of each variable name included in the output of the run_analysis (that in fact shows averages of each variable), its name, class and standar values. 

The number in front of the variable name indicates the maximun number of digits or decimals

1. Subject  2
  * Number of the Subject that performed the activity
  * Integer
  * Values Between 1 and 30. (Total of subjects)

2. Activity
- Ativity performed by the indicated subject.
- Character
* Walkig
* Walking Upstairs
* Walking Downtairs
* Standing
* Sitting
* Laying


3. TimeBodyAccMeanX   8
  - Time Body Acceleration on the X axis mean
  - Numeric
  - Absolute value < 1

4. TimeBodyAccMeanY   8
- Time Body Acceleration on the Y axis mean
- Numeric
- Absolute value < 1

5. TimeBodyAccMeanZ   8
- Time Body Acceleration on the Z axis mean
- Numeric
- Absolute value < 1

6. TimeBodyAccStdX   8
- Time Body Acceleration on the X axis Standard Deviation
- Numeric (negative)
- Absolute value < 1

7. TimeBodyAccStdY   8
- Time Body Acceleration on the Y axis Standard Deviation
- Numeric (negative)
- Absolute value < 1

8. TimeBodyAccStdZ   8 
- Time Body Acceleration on the z axis Standard Deviation
- Numeric (negative)
- Absolute value < 1


9. TimeGravitytAccMeanX   8
- Time Gravity Acceleration Mean on the X axis
- Numeric
- Absolute value < 1

10. TimeGravitytAccMeanY   8
- Time Gravity Acceleration Mean on the Y axis
- Numeric
- Absolute value < 1

12. TimeGravitytAccMeanZ   8
- Time Gravity Acceleration Mean on the Z axis
- Numeric
- Absolute value < 1

13. TimeGravitytAccStdX   8
- Time Gravity Acceleration Standard Deviation on the X axis
- Numeric (Negative)
- Absolute value < 1

14. TimeGravitytAccStdY   8
- Time Gravity Acceleration Standard Deviation on the Y axis
- Numeric (Negative)
- Absolute value < 1

15. TimeGravitytAccStdZ   8
- Time Gravity Acceleration Standard Deviation on the Z axis
- Numeric (Negative)
- Absolute value < 1

16. TimeBodyAccJerkMeanX   8
- Time Body Acceleration Jerk Mean on the X axis
- Numeric
- Absolute Value < 1

17. TimeBodyAccJerkMeanY   8
- Time Body Acceleration Jerk Mean on the Y axis
- Numeric
- Absolute Value < 1

18. TimeBodyAccJerkMeanZ   8
- Time Body Acceleration Jerk Mean on the Z axis
- Numeric
- Absolute Value < 1

19. TimeBodyAccJerkStdX   8
- Time Body Acceleration Jerk Standard Deviation on the X axis
- Numeric (Negative)
- Absolute Value < 1

20. TimeBodyAccJerkStdY   8
- Time Body Acceleration Jerk Standard Deviation on the Y axis
- Numeric (Negative)
- Absolute Value < 1

21. TimeBodyAccJerkStdZ   8
- Time Body Acceleration Jerk Standard Deviation on the Z axis
- Numeric (Negative)
- Absolute Value < 1

22. TimeBodyGyroMeanX   8
- Time Body Gyro Mean on the X axis
- Numeric
- Absolute value < 1

23. TimeBodyGyroMeanY   8
- Time Body Gyro Mean on the Y axis
- Numeric
- Absolute value < 1

24. TimeBodyGyroMeanZ   8
- Time Body Gyro Mean on the Z axis
- Numeric
- Absolute value < 1

25. TimeBodyGyroStdX   8
- Time Body Gyro Mean on the X axis
- Numeric
- Absolute value < 1

26. TimeBodyGyroStdY   8
- Time Body Gyro Mean on the Y axis
- Numeric
- Absolute value < 1

27. TimeBodyGyroStdZ   8
- Time Body Gyro Mean on the Z axis
- Numeric
- Absolute value < 1

28. TimeBodyGyroJerkMeanX   8
- On the X axis
- Numeric (negative)
- Absolute value < 1

29. TimeBodyGyroJerkMeanY   8
- On the Y axis
- Numeric (negative)
- Absolute value < 1

30. TimeBodyGyroJerkMeanZ   8
- On the Z axis
- Numeric (negative)
- Absolute value < 1

31. TimeBodyGyroJerkStdX   8
- Time Body Gyro Jerk Standard Deviation on the X axis
- Numeric (negative)
- Absolute value < 1

32. TimeBodyGyroJerkStdY   8
- Time Body Gyro Jerk Standard Deviation on the Y axis
- Numeric (negative)
- Absolute value < 1

33. TimeBodyGyroJerkStdZ   8
- Time Body Gyro Jerk Standard Deviation on the Z axis
- Numeric (negative)
- Absolute value < 1

34. TimeBodyAccMagMean   8
- Time Body Acceleration Magnitude Mean
- Numeric (negative)
- Absolute value < 1

35. TimeBodyAccMagStd   8   
- Time Body Acceleration Magnitude Standard Deviation
- Numeric (negative)
- Absolute value < 1

36. TimeGravitytAccMagMean   8
- Time Gravity Acceleration Magnitude Mean
- Numeric (negative)
- Absolute value < 1

37. TimeGravitytAccMagStd   8
- Time Gravity Acceleration Magnitude Standard Deviation
- Numeric (negative)
- Absolute value < 1

38. TimeBodyAccJerkMagMean   8
- Time Body Acceleration Jerk Magnitude Mean
- Numeric (negative)
- Absolute value < 1

39. TimeBodyAccJerkMagStd   8 
- Time Body Acceleration Jerk Magnitude Standard Deviation
- Numeric (negative)
- Absolute value < 1

40. TimeBodyGyroMagMean   8
- Time Body Gyro Magnitude Mean
- Numeric (negative)
- Absolute value < 1

41. TimeBodyGyroMagStd   8
- Time Body Gyro Magnitude Standard Deviation
- Numeric (negative)
- Absolute value < 1

42. TimeBodyGyroJerkMagMean   8 
- Time Body Gyro Jerk Magnitude  Mean
- Numeric (negative)
- Absolute value < 1

43. TimeBodyGyroJerkMagStd   8 
- Time Body Gyro Jerk Magnitude Standard Deviation
- Numeric (negative)
- Absolute value < 1

44. FrecBodyAccMeanX 
- Frequency Body Acceleration Mean on the X axis
- Numeric (Negative)
- Absolute value < 1

45. FrecBodyAccMeanY 
- Frequency Body Acceleration Mean on the Y axis
- Numeric (Negative)
- Absolute value < 1

46. FrecBodyAccMeanZ 
- Frequency Body Acceleration Mean on the Z axis
- Numeric (Negative)
- Absolute value < 1

47. FrecBodyAccStdX 
- Frequency Body Acceleration Standard Deviation on the X axis
- Numeric (Negative)
- Absolute value < 1

48. FrecBodyAccStdY
- Frequency Body Acceleration Standard Deviation on the Y axis
- Numeric (Negative)
- Absolute value < 1

49. FrecBodyAccStdZ
- Frequency Body Acceleration Standard Deviation on the Z axis
- Numeric (Negative)
- Absolute value < 1

50. FrecBodyAccMeanFreqX       
- Frequency Body Acceleration Mean on the X axis
- Numeric (Negative)
- Absolute value < 1

51. FrecBodyAccMeanFreqY
- Frequency Body Acceleration Mean on the Y axis
- Numeric (Negative)
- Absolute value < 1

52. FrecBodyAccMeanFreqZ
- Frequency Body Acceleration Mean on the Z axis
- Numeric (Negative)
- Absolute value < 1

53. FrecBodyAccJerkMeanX  
- Frequency Body Acceleration Jerk Mean on the X axis
- Numeric (Negative)
- Absolute value < 1

54. FrecBodyAccJerkMeanY
- Frequency Body Acceleration Jerk Mean on the Y axis
- Numeric (Negative)
- Absolute value < 1

55. FrecBodyAccJerkMeanZ
- Frequency Body Acceleration Jerk Mean on the Z axis
- Numeric (Negative)
- Absolute value < 1

56. FrecBodyAccJerkStdX 
- Frequency Body Acceleration Standard Deviation on the X axis
- Numeric
- Absolute value < 1

57. FrecBodyAccJerkStdY
- Frequency Body Acceleration Standard Deviation on the Y axis
- Numeric
- Absolute value < 1

58. FrecBodyAccJerkStdZ 
- Frequency Body Acceleration Standard Deviation on the Z axis
- Numeric
- Absolute value < 1

59. FrecBodyAccJerkMeanFreqX 
- Frequency Body Acceleration Jerk Mean Frequency on the X axis
- Numeric
- Absolute value < 1

60. FrecBodyAccJerkMeanFreqY
- Frequency Body Acceleration Jerk Mean Frequency on the Y axis
- Numeric
- Absolute value < 1

61. FrecBodyAccJerkMeanFreqZ
- Frequency Body Acceleration Jerk Mean Frequency on the Z axis
- Numeric
- Absolute value < 1

62. FrecBodyGyroMeanX
- Frequency Body Gyro Mean on the X axis
- Numeric
- Absolute value < 1

63. FrecBodyGyroMeanY 
- Frequency Body Gyro Mean on the Y axis
- Numeric
- Absolute value < 1

64. FrecBodyGyroMeanZ
- Frequency Body Gyro Mean on the Z axis
- Numeric
- Absolute value < 1

65. FrecBodyGyroStdX
- Frequency Body Gyro Standard Deviation on the X axis
- Numeric
- Absolute value < 1

66. FrecBodyGyroStdY
- Frequency Body Gyro Standard Deviation on the Y axis
- Numeric
- Absolute value < 1

67. FrecBodyGyroStdZ
- Frequency Body Gyro Standard Deviation on the Z axis
- Numeric
- Absolute value < 1

68. FrecBodyGyroMeanFreqX 
- Frequency Body Gyro Mean Frequency on the X axis
- Numeric
- Absolute value < 1

69. FrecBodyGyroMeanFreqY
- Frequency Body Gyro Mean Frequency on the Y axis
- Numeric
- Absolute value < 1

70. FrecBodyGyroMeanFreqZ
- Frequency Body Gyro Mean Frequency on the Z axis
- Numeric
- Absolute value < 1


71. FrecBodyAccMagMean
- Frequency Body Acceleration Magnitude Mean
- Numeric
- Absolute value < 1

72. FrecBodyAccMagStd
- Frequency Body Acceleration Magnitude Standard Deviation
- Numeric
- Absolute value < 1

73. FrecBodyAccMagMeanFreq
- Frequency Body Acceleration Magnitude Frequency
- Numeric
- Absolute value < 1

74. FrecBodyAccJerkMagMean
- Frequency Body Acceleration Magnitude Mean
- Numeric
- Absolute value < 1

75. FrecBodyAccJerkMagStd
- Frequency Body Acceleration Magnitude Standard Deviation
- Numeric [-1, 1]
- Absolute value < 1

76. FrecBodyAccJerkMagMeanFreq
- Frequency Body Gyro Magnitude Mean Frequency
- Numeric [-1, 1]
- Absolute value < 1

77. FrecBodyGyroMagMean
- Frequency Body Gyro Magnitude Mean
- Numeric [-1, 1]
- Absolute value < 1

78. FrecBodyGyroMagStd
- Frequency Body Gyro Magnitude Standard Deviation
- Numeric [-1, 1]
- Absolute value < 1

79. FrecBodyGyroMagMeanFreq
- Frequency Body Gyro Jerk Magnitude Mean Frquency
- Numeric [-1, 1]
- Absolute value < 1

80. FrecBodyGyroJerkMagMean
- Frequency Body Gyro Jerk Magnitude Mean
- Numeric [-1, 1]
- Absolute value < 1

81. FrecBodyGyroJerkMagStd
- Frequency Body Gyro Jerk Magnitude Standard Deviation
- Numeric [-1, 1]
- Absolute value < 1

82. FrecBodyGyroJerkMagMeanFreq
- Frequency Body Gyro Jerk Magnitude Mean Frequency
- Numeric [-1, 1]
- Absolute value < 1
